export default () => ({
  APP_NAME: process.env.APP_NAME || 'Employee Query Agent',
  APP_VERSION: process.env.APP_VERSION || '1.0.0',
  ENVIRONMENT: process.env.ENVIRONMENT || 'development',
  DEBUG: process.env.DEBUG === 'true',
  LOG_LEVEL: process.env.LOG_LEVEL || 'info',
  DB_HOST: process.env.DB_HOST || 'localhost',
  DB_PORT: parseInt(process.env.DB_PORT || '', 10) || 3306,
  DB_USERNAME: process.env.DB_USERNAME || 'root',
  DB_PASSWORD: process.env.DB_PASSWORD || 'password',
  DB_DATABASE: process.env.DB_DATABASE || 'employee_agent',
  LLM_PROVIDER: process.env.LLM_PROVIDER || 'qwen',
  CLAUDE_API_KEY: process.env.CLAUDE_API_KEY || '',
  CLAUDE_MODEL: process.env.CLAUDE_MODEL || 'claude-opus-4-6',
  CLAUDE_BASE_URL: process.env.CLAUDE_BASE_URL || '',
  OPEN_API_KEY: process.env.OPEN_API_KEY || '',
  OPEN_MODEL: process.env.OPEN_MODEL || 'qwen-plus',
  OPEN_BASE_URL: process.env.OPEN_BASE_URL || 'https://dashscope.aliyuncs.com/compatible-mode/v1',
  AGENT_MAX_ITERATIONS: parseInt(process.env.AGENT_MAX_ITERATIONS || '', 10) || 6,
  REDIS_HOST: process.env.REDIS_HOST || 'localhost',
  REDIS_PORT: parseInt(process.env.REDIS_PORT || '', 10) || 6379,
  PORT: parseInt(process.env.PORT || '', 10) || 8000,
});
